spring:
  profiles: default
  application:
    name: Halfdev
  banner:
    charset: UTF-8
    location: classpath:halfdev.txt

logging:
  level:
    org.springframework: debug
    com.halfdev.my: debug

---

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: halfdev
    url: jdbc:mysql://localhost:3306/bootcommunity?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: bootcommunity
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    hibernate:
#      ddl-auto: validate

#mysql:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/bootcommunity?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
#    username: bootcommunity
#    password: halfdev
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    hibernate:
#      ddl-auto: validate

---

logging:
  config: classpath:logback.xml

spring:
  profiles: dev
  application:
    name: Halfdev
  banner:
    charset: UTF-8
    location: classpath:halfdev.txt

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 1000
    default-statement-timeout: 30
  type-aliases-package: com.halfdev.my.domain
  type-handlers-package: com.halfdev.my.domain